#!/usr/bin/env python3
"""Regenerate registers/README.md and registers/input-registers.csv
from registers/input-registers.json.

    python tools/gen_tables.py

Edit the JSON, never the generated files.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "registers" / "input-registers.json"


def main():
    spec = json.loads(SPEC.read_text(encoding="utf8"))

    rows = []
    md = ["<!-- GENERATED by tools/gen_tables.py -- edit input-registers.json -->",
          "", "# PS7000 read-only Modbus register map", "",
          f"**Protocol:** {spec['protocol']}  ",
          f"**Function code:** 0x04 (read input registers)  ",
          f"**Scope:** {spec['scope']}", "",
          "## Before you read a single register", "",
          f"1. **{spec['addressing']['note']}** {spec['addressing']['example']}",
          f"2. **Word order for 32-bit values is {spec['byteOrder']['u32_f32'].split('.')[0]}.** "
          f"{spec['byteOrder']['warning']}",
          f"3. Serial defaults: {spec['serial']['frame']}, "
          f"slave {spec['serial']['slaveAddress']}, baud {spec['serial']['baudRate']}.",
          "", f"> {spec['firmware']}", ""]

    for block in spec["blocks"]:
        md += [f"## {block['name']}", ""]
        if "readAdvice" in block:
            md += [block["readAdvice"], ""]
        md += ["| Register | Field | Type | Unit | Description |",
               "|---:|---|---|---|---|"]
        for r in block["registers"]:
            unit = r.get("unit", "")
            if "scale" in r:
                unit = (unit + " " if unit else "") + f"(x{r['scale']})"
            desc = r["desc"].replace("|", "\\|")
            if r.get("primary"):
                desc = "**" + desc + "**"
            if "since" in r:
                desc += f" _(firmware {r['since']})_"
            md.append(f"| {r['reg']} | `{r['field']}` | {r['type']} | {unit} | {desc} |")
            rows.append({"block": block["name"], "register": r["reg"],
                         "field": r["field"], "type": r["type"],
                         "unit": r.get("unit", ""), "scale": r.get("scale", ""),
                         "since": r.get("since", ""), "description": r["desc"]})
        md.append("")

    (ROOT / "registers" / "README.md").write_text("\n".join(md), encoding="utf8")

    with open(ROOT / "registers" / "input-registers.csv", "w", newline="",
              encoding="utf8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    print(f"wrote registers/README.md and registers/input-registers.csv "
          f"({len(rows)} registers)")


if __name__ == "__main__":
    main()
